name: Michael Mott
description: This is the Personal Website of Michael Warren Mott.
author: Michael Mott
author_email: michaelwarrenmott@gmail.com
baseurl: /
url: "http://localhost:4000/"

markdown: rdiscount
permalink: /:categories/:title


pygments: false

safe:        false
auto:        true
server:      false
source:      .
plugins:     ./_plugins
future:      true