name: Michael Mott
description: This is the Personal Website of Michael Mott.
author: Michael Mott
author_email: michaelwarrenmott@gmail.com
category_dir: /
baseurl: /
url: http://localhost:4000/

markdown: rdiscount
permalink: /:categories/:title


pygments: false

safe:        false
auto:        true
server:      false
source:      .
destination: ./_site
plugins:     ./_plugins
future:      true
markdown:    maruku
permalink:   date