name: Michael Mott
description: This is the Personal Website of Michael Warren Mott.
author: Michael Mott
author_email: michaelwarrenmott@gmail.com
baseurl: ""
url: "http://localhost:4000"

markdown: kramdown
permalink: /:categories/:title

jekyll_ga:
  service_account_email:    754523168464@developer.gserviceaccount.com
  key_file: f0e4032aa4552a88f8395232675ffcdef5e24e81-privatekey.p12
  key_secret: notasecret   
  profileID: 78205423
  start: last month         
  end: now               
  metric: ga:pageviews    
  segment:                 
  filters:                 
  sort: false   
exclude: jekyll-ga.rb

pygments: false

safe:        false
auto:        true
server:      false
source:      .
plugins:     ./_plugins
future:      true

production_url: www.mikemott.com