name: Michael Mott
description: This is the Personal Website of Michael Warren Mott.
author: Michael Mott
author_email: michaelwarrenmott@gmail.com
baseurl: /personal
url: "mwmott.github.io"

markdown: redcarpet
permalink: /:categories/:title

analytics:
	provider: google
		tracking_id: 'UA-45090266-1'

pygments: false

safe:        false
auto:        true
server:      false
source:      .
plugins:     ./_plugins
future:      true

production_url: www.mikemott.com